site_name: Convutell
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  palette:
        primary: 'black'
        accent: 'green'
  
extra:
  alternate:
    - name: English
      link: /en/ 
      lang: en
    - name: PortuguÃªs
      link: /pt/
      lang: de
  social:
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/in/clayttonsilva/
    - icon: fontawesome/brands/github
      link: https://github.com/claytonlovin/convutell
    - icon: fontawesome/brands/twitter
      link: https://www.linkedin.com/in/clayttonsilva/
